### ISSUE TITLE
strored error 

### ISSUE THREAD

**Issue by rookie-iosers** [QuickBirdEng/kotlin-snapshot-testing#1]
java.lang.AssertionError: Stored snapshot to: /data/data/com.quickbird.android_example/files/snapshot/ComposeScreenshotTest/mainScreenScreenshot_reference.png
at com.quickbird.snapshot.FileSnapshotting_snapshotKt.snapshot(FileSnapshotting+snapshot.kt:36)
at com.quickbird.snapshot.JUnitFileSnapshotTest.snapshot(JUnitFileSnapshottingTest.kt:18)
at com.quickbird.snapshot.AndroidFileSnapshotTest.snapshotToFilesDir(AndroidFileSnapshotTest.kt:9)
at com.quickbird.snapshot.AndroidFileSnapshotTest.snapshotToFilesDir$default(AndroidFileSnapshotTest.kt:5)
at com.quickbird.android_example.ComposeScreenshotTest$mainScreenScreenshot$1.invokeSuspend(ComposeScreenshotTest.kt:20)

**Comment by balazstothofficial** [comment]
Hi, 
that's the expected behavior if you newly record a snapshot. If you now set the flag `record=false`, then on the next run the test will compare the new screenshot with `mainScreenScreenshot_reference.png` which you just recorded.
Or does something else not work as expected?

**Comment by rookie-iosers** [comment]
I just set the AndroidFileSnapshotTest(record = true) in ComposeScreenshotTest and didn't make any other code changes.

**Comment by balazstothofficial** [comment]
Yes, that's how it should be. Now the snapshot is recorded. If you set now `AndroidFileSnapshotTest(record = false)` then the test should pass. 
When `record=true` is set then you create a new snapshot and the test fails, when `record=false` is set then you create a snapshot and try to compare it to an existing reference.

**Comment by balazstothofficial** [comment]
If you want to have a look at the stored snapshot, just go to the path in the error stack (/data/data/com.quickbird.android_example/files/snapshot/ComposeScreenshotTest/mainScreenScreenshot_reference.png).

**Comment by rookie-iosers** [comment]
> Yes, that's how it should be. Now the snapshot is recorded. If you set now then the test should pass. When is set then you create a new snapshot and the test fails, when is set then you create a snapshot and try to compare it to an existing reference.`AndroidFileSnapshotTest(record = false)``record=true``record=false`

i think i get it. Thanks
