### ISSUE TITLE
Support for configuring diff tolerance

### ISSUE THREAD

**Issue by yschimke** [QuickBirdEng/kotlin-snapshot-testing#3]
Is there a good sample of setting some tolerance for diffs?

**Comment by yschimke** [comment]
A quick go at this, feel free to use this code for this library.

https://github.com/joreilly/Confetti/pull/424/files#diff-981585b09fd871b242637574c90f59fd32d00251690a7f4fb71ed80311a99feb

**Comment by balazstothofficial** [comment]
Added: https://github.com/QuickBirdEng/kotlin-snapshot-testing/pull/6
